#cloud-config
ssh_pwauth: false
users:
  - name: yc-user
    groups: sudo
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh-authorized-keys:
      - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDNJwQoQdYdt86rzaRqU/QXOuW672c+ITshYx4d6TXRG2xR8b9tKjx7egXFLXsT+evGeBIuS2Q/k+5RGWNSjPqSC6tbshkjsDnuD98AEVthb47MIDD3WwkkOZPAoO59OfS1dsOG3ehue/+BwSJr/vcGwqVIHcrkzOUHjlklobdbieGR1dG6A9aedYEfLZbuypfUaVrkS6eO09GAVsS/St1kGPv4XGuq19MK0AZQs6QoIAu5YhcC1OLv4vj1tlULo+V5BVx9SJ7A6VtAsg6jbFpORuDSXqy0Hx4i5VEo/ukeR8bhJDiSoAl/WTVA5Ln730GLzf8zDn/RauV6sQQdnCzEg+jAfj9nRjo+CpV0GA7wzy//01bDFRbUVmaFSqm0dEe9EvzF7u/jadmxOHbWK8zcMZaW9nLqMbfRxJw9xSryrUW8HJ/xDkCUFx4FAyPIvUfd0Bema8AlUhI3QQ3FfmfgtbUyJahfy5qPDnQ4wipQjzo2v/rGicGPjfsacyKWR7c= avgroup\k.pospelov@AV-NB-6027352'
package_update: true
package_upgrade: true
packages:
  - git
runcmd:
  - git clone https://github.com/Otus-DevOps-2023-07/poskon_infra.git /home/yc-user/poskon_infra
  - cd /home/yc-user/poskon_infra
  - git checkout cloud-testapp
  - /home/yc-user/poskon_infra/install_ruby.sh && /home/yc-user/poskon_infra/install_mongodb.sh && /home/yc-user/poskon_infra/deploy.sh
  - rm -r /home/yc-user/poskon_infra
